# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed10222195140d5eeb2423b9b8887f4a1fb4e9d771304e8ddb051ceb8a1b31acd42141d7867400b2fb25ce172ca0c80557b0b31e7a33ec9acf70b6894d244339

test:
  secret_key_base: 86e60ce0091926de521e4c7fa60485594ae046f2e25dd5c013cf2ec1db1c0f80cea1a878be6221a06646481607d7f2168cc4a8817d7af18562d3593d6936c13a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
